project:
  type: website

website:
  title: "Nathan Miller"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Annath
      - icon: linkedin
        href: https://www.linkedin.com/in/nomiller/
format:
  html:
    theme: cosmo
    css: styles.css



